// Auto-generated complete production fallback data matching server/src/seed.ts

export const FALLBACK_SERVICES: any[] = [
    {
      slug: 'elevator-maintenance',
      title: 'Elevator Maintenance (AMC)',
      keywordHighlight: 'Comprehensive & Non-Comprehensive AMC',
      categoryBadge: 'PREVENTATIVE MAINTENANCE PROGRAM',
      metaTitle: 'Lift AMC Maintenance in Navi Mumbai & Pune | NSE',
      metaDescription: 'Comprehensive & Non-Comprehensive lift AMC maintenance for housing societies and commercial towers. Multi-brand expertise, genuine OEM spares.',
      h1: 'Customized Lift AMC Maintenance Programs',
      leadText: 'Tailored maintenance agreements for housing societies (CHS), commercial IT parks, and hospitals across Navi Mumbai and Pune. Prevent breakdowns and ensure round-the-clock passenger safety.',
      checklist: [
        'Monthly comprehensive 25-point safety inspection and lubrication routine',
        'Guaranteed 24/7 emergency breakdown dispatch with rapid emergency response',
        '100% genuine OEM spare parts for Schindler, KONE, OTIS, Johnson, and TKE lifts',
      ],
      workflowSteps: [
        { step: '01', title: 'Initial 25-Point Hoistway Audit', desc: 'Detailed assessment of traction ropes, brake shoes, door interlocks, and control panels.' },
        { step: '02', title: 'Customized AMC Plan Formulation', desc: 'Formulation of Comprehensive or Non-Comprehensive contract matching society budget.' },
        { step: '03', title: 'Monthly Scheduled Servicing', desc: 'Rigorous mechanical and electrical checks with digital service ticket handover.' },
        { step: '04', title: 'Annual Comprehensive Safety Audit', desc: 'Exhaustive 25-point electromechanical audit and detailed safety condition report.' },
      ],
      equipmentBrands: ['Schindler', 'KONE', 'OTIS', 'Johnson', 'thyssenkrupp'],
      faqs: [
        { question: 'What is the difference between Comprehensive and Non-Comprehensive AMC?', answer: 'Comprehensive AMC covers all replacement spare parts, breakdown calls, and routine servicing. Non-Comprehensive AMC covers all routine service visits and breakdown labor, with spare parts billed separately at pre-agreed rates.' },
        { question: 'Do you service lifts in older Co-operative Housing Societies?', answer: 'Yes. Over 70% of our portfolio includes high-rise and mid-rise residential societies across Navi Mumbai and Pune.' },
      ],
      status: 'published',
    },
    {
      slug: 'elevator-repair',
      title: '24/7 Lift Breakdown &',
      keywordHighlight: 'Emergency Entrapment Repair',
      categoryBadge: '24/7 EMERGENCY RESPONSE',
      metaTitle: '24/7 Emergency Lift Repair & Rescue in Pune & Mumbai | NSE',
      metaDescription: 'Rapid 24/7 emergency elevator repair & passenger entrapment rescue. 15+ certified engineers across Navi Mumbai & Pune. Prompt on-site dispatch.',
      h1: '24/7 Emergency Lift Breakdown & Passenger Rescue',
      leadText: 'Immediate emergency response for sudden lift stoppages, door sensor failures, power phase trips, and passenger entrapments across Navi Mumbai and Pune.',
      checklist: [
        'Prompt on-site emergency dispatch across Navi Mumbai and Pune',
        'Rapid-response vehicles stocked with multi-brand genuine OEM replacement parts',
        'Background-verified, experienced technicians following strict safety and operational protocols',
      ],
      workflowSteps: [
        { step: '01', title: 'Immediate GPS Dispatch', desc: 'Central dispatch assigns nearest field technician van upon distress call.' },
        { step: '02', title: 'Safe Passenger Extraction', desc: 'Safe mechanical brake release, leveling at landing, and calm passenger exit.' },
        { step: '03', title: 'Root Cause Diagnostics', desc: 'Microprocessor error log review and safety interlock circuit verification.' },
        { step: '04', title: 'Safe System Restoration', desc: 'Genuine spare replacement and multi-cycle test run before handover.' },
      ],
      equipmentBrands: ['Schindler', 'KONE', 'OTIS', 'Johnson', 'thyssenkrupp'],
      faqs: [
        { question: 'What is your average arrival time for trapped passengers?', answer: 'We maintain prompt on-site emergency response dispatch across our coverage corridors in Navi Mumbai and Pune.' },
      ],
      status: 'published',
    },
    {
      slug: 'elevator-modernization',
      title: 'Turnkey Lift Modernization',
      keywordHighlight: '& Performance Upgrades',
      categoryBadge: 'MODERNIZATION & RETROFITS',
      metaTitle: 'Elevator Modernization & Controller Upgrades in Mumbai & Pune | NSE',
      metaDescription: 'Upgrade aging elevator controllers, VVVF drives, door operators, and cab interiors. Save up to 30% vs OEM direct quotes with genuine spares.',
      h1: 'Turnkey Lift Modernization & Energy-Efficient Upgrades',
      leadText: 'Revitalize aging elevators in residential societies and commercial complexes. Upgrade controllers, VVVF drives, door operators, and cab aesthetics with OEM precision at approximately 30% lower cost.',
      checklist: [
        'Advanced VVVF microprocessors eliminating jerky starts and rough stops',
        'Energy-efficient regenerative drives cutting electricity consumption by up to 35%',
        'Premium architectural cab redesigns including false ceilings, LED lighting, and SS panels',
      ],
      workflowSteps: [
        { step: '01', title: 'Component Longevity Assessment', desc: 'Evaluation of existing guide rails, car slings, counterweights, and worm gearboxes.' },
        { step: '02', title: 'Engineering Retrofit Design', desc: 'Selection of modern controllers, digital leveling sensors, and door operators.' },
        { step: '03', title: 'Phased Installation', desc: 'Minimizing building disruption by modernizing one lift car at a time.' },
        { step: '04', title: 'Testing & Safety Handover', desc: 'Full-load safety gear testing, ARD verification, and client handover certification.' },
      ],
      equipmentBrands: ['Schindler', 'KONE', 'OTIS', 'Johnson', 'thyssenkrupp'],
      faqs: [
        { question: 'Why should a society modernize instead of replacing the entire elevator?', answer: 'Modernization retains sound structural elements (rails, counterweights, slings) and upgrades the brains and moving parts (controller, drives, door operators), costing up to 60% less than full replacement.' },
      ],
      status: 'published',
    },
    {
      slug: 'safety-inspections-code-compliance',
      title: 'Lift Safety Audits &',
      keywordHighlight: 'Comprehensive Safety Audits',
      categoryBadge: '25-POINT SAFETY AUDIT',
      metaTitle: 'Elevator Safety Audits & Multi-Point Testing | NSE',
      metaDescription: 'Comprehensive 25-point lift safety audits, ARD drop testing, and preventative inspection in Navi Mumbai and Pune.',
      h1: 'Comprehensive Lift Safety Inspections & Engineering Audits',
      leadText: 'Ensure your building elevators maintain peak mechanical safety and operational reliability with expert 25-point safety audits from experienced engineers.',
      checklist: [
        'Complete 25-point comprehensive health and safety inspection',
        'Automatic Rescue Device (ARD) and emergency battery backup testing',
        'Detailed safety audit documentation and engineering condition assessments',
      ],
      workflowSteps: [
        { step: '01', title: 'Preliminary Safety Audit', desc: 'Examination of safety gears, governor ropes, door locks, and electrical grounding.' },
        { step: '02', title: 'Audit Report Generation', desc: 'Detailed audit report highlighting prioritized mechanical rectifications and component health.' },
        { step: '03', title: 'Violation Rectification', desc: 'Expedited replacement of worn cables, safety switches, and interlocks.' },
        { step: '04', title: 'Safety Certification & Sign-Off', desc: 'Complete safety verification sign-off and preventive maintenance roadmap handover.' },
      ],
      equipmentBrands: ['Schindler', 'KONE', 'OTIS', 'Johnson', 'thyssenkrupp'],
      faqs: [
        { question: 'What does our 25-point elevator safety audit cover?', answer: 'Our comprehensive audit evaluates traction ropes, brake assemblies, door interlocks, car top safety gear, ARD batteries, and hoistway switches to identify safety hazards before failures occur.' },
      ],
      status: 'published',
    },
    {
      slug: 'elevator-cab-remodeling',
      title: 'Elevator Cab Interior',
      keywordHighlight: 'Remodeling & Aesthetic Upgrades',
      categoryBadge: 'CAB ARCHITECTURAL UPGRADES',
      metaTitle: 'Elevator Cab Interior Remodeling in Pune & Mumbai | NSE',
      metaDescription: 'Transform worn residential and commercial elevator cabs with SS hairline panels, false ceilings, granite flooring, and digital display fixtures.',
      h1: 'Elevator Cab Interior Remodeling & Refurbishment',
      leadText: 'Modernize elevator car interiors with designer stainless steel finishes, energy-saving LED lighting, durable flooring, and responsive car operating panels (COP).',
      checklist: [
        'SS 304 hairline, gold mirror, and scratch-resistant honeycomb wall panels',
        'Lightweight composite and granite tile flooring compliant with weight limits',
        'Modern touch-screen COPs and Braille-embossed pushbuttons',
      ],
      workflowSteps: [
        { step: '01', title: 'Material Selection & Weight Calculation', desc: 'Choosing aesthetics while ensuring overall cab weight remains within counterweight balance limits.' },
        { step: '02', title: 'Precision Laser Cutting', desc: 'Custom pre-fabrication of stainless steel sheets and ceiling light panels.' },
        { step: '03', title: 'Rapid On-Site Cladding', desc: 'Installation executed within 48-72 hours to minimize elevator downtime.' },
        { step: '04', title: 'Final Balancing & Polish', desc: 'Counterweight adjustment, safety clearance verification, and protective film removal.' },
      ],
      equipmentBrands: ['Schindler', 'KONE', 'OTIS', 'Johnson', 'thyssenkrupp'],
      faqs: [
        { question: 'Will cab remodeling overload our elevator motor?', answer: 'No. Our engineers calculate tare weight changes and adjust counterweights to ensure precision mechanical balance and smooth operation.' },
      ],
      status: 'published',
    },
    {
      slug: 'hydraulic-traction-conversions',
      title: 'Hydraulic & Traction',
      keywordHighlight: 'Conversions & Gearbox Overhauls',
      categoryBadge: 'HEAVY MECHANICAL ENGINEERING',
      metaTitle: 'Elevator Traction Conversion & Mechanical Overhauls | NSE',
      metaDescription: 'Heavy mechanical elevator engineering: hydraulic cylinder retrofits, gearless machine conversions, and traction rope replacements across Mumbai & Pune.',
      h1: 'Hydraulic & Traction Elevator Mechanical Overhauls',
      leadText: 'Expert mechanical repairs for worm-and-gear traction machines, gearless permanent magnet motors, hydraulic power packs, and hoisting wire ropes.',
      checklist: [
        'High-tensile Indian Standard wire rope replacements with calibrated tensioning',
        'Precision gearbox bearing replacements and synthetic lubricant overhauls',
        'Hydraulic seal replacements and pressure relief valve calibration',
      ],
      workflowSteps: [
        { step: '01', title: 'Mechanical Stress Diagnostics', desc: 'Measurement of sheave groove wear, backlash, and hydraulic pressure decay.' },
        { step: '02', title: 'Heavy Rigging & Disassembly', desc: 'Secure hoisting and precision disassembly of machine components.' },
        { step: '03', title: 'Bearing & Seal Replacement', desc: 'Installation of high-grade SKF bearings and OEM hydraulic packing.' },
        { step: '04', title: 'Full-Load Calibration', desc: 'Load testing and vibration frequency analysis to ensure silky smooth transit.' },
      ],
      equipmentBrands: ['Schindler', 'KONE', 'OTIS', 'Johnson', 'thyssenkrupp'],
      faqs: [
        { question: 'How often should elevator hoisting ropes be replaced?', answer: 'Hoisting ropes should be inspected monthly during routine AMC and replaced whenever crown wire breaks or diameter reduction exceeds standard engineering thresholds.' },
      ],
      status: 'published',
    },
    {
      slug: 'non-proprietary-elevator-service',
      title: 'Multi-Brand Expertise &',
      keywordHighlight: 'Genuine OEM Spares Maintenance',
      categoryBadge: 'MULTI-BRAND EXCELLENCE',
      metaTitle: 'Multi-Brand Elevator Maintenance with Genuine Spares | NSE',
      metaDescription: 'One trusted partner for Schindler, KONE, OTIS, Johnson, and thyssenkrupp elevators with genuine OEM spares at ~30% lower cost than going direct.',
      h1: 'Multi-Brand Elevator Service & Genuine OEM Spare Parts',
      leadText: 'One reliable partner for all your elevators. We maintain Schindler, KONE, OTIS, Johnson, and thyssenkrupp systems using genuine OEM spare parts, backed by transparent pricing with no hidden surcharges.',
      checklist: [
        '100% genuine OEM spare parts inventory across all 5 major elevator brands',
        'Over 15 certified field engineers with deep multi-brand diagnostic expertise',
        'Transparent billing with typical 30% savings compared to OEM direct AMC quotes',
      ],
      workflowSteps: [
        { step: '01', title: 'Multi-Brand Fleet Audit', desc: 'Comprehensive audit of controllers, drives, and mechanical parts across your complex.' },
        { step: '02', title: 'Genuine Parts Sourcing', desc: 'Procurement of original OEM components with verified manufacturer warranties.' },
        { step: '03', title: 'Preventative Calibrations', desc: 'Brand-specific maintenance protocols strictly following OEM technical guidelines.' },
        { step: '04', title: 'Quarterly Performance Review', desc: 'Transparent logbook reviews with housing society management committees.' },
      ],
      equipmentBrands: ['Schindler', 'KONE', 'OTIS', 'Johnson', 'thyssenkrupp'],
      faqs: [
        { question: 'Do you use genuine OEM spare parts?', answer: 'Yes. We source and install 100% genuine OEM replacement parts for Schindler, KONE, OTIS, Johnson, and thyssenkrupp systems.' },
      ],
      status: 'published',
    },
    {
      slug: 'elevator-installation',
      title: 'New Elevator Design &',
      keywordHighlight: 'Turnkey Installation Services',
      categoryBadge: 'ENGINEERED INSTALLATIONS',
      metaTitle: 'New Lift Installation in Navi Mumbai & Pune | NSE',
      metaDescription: 'Engineered passenger and freight elevator installation for residential buildings, commercial towers, and hospitals. Multi-brand engineering expertise.',
      h1: 'New Elevator Design, Engineering & Installation',
      leadText: 'Turnkey elevator installation for new residential complexes, commercial developments, and hospital facilities across Navi Mumbai and Pune.',
      checklist: [
        'Machine-Room-Less (MRL) gearless traction lifts maximizing usable terrace space',
        'Hospital stretcher bed lifts with ultra-smooth digital floor leveling',
        'Full structural alignment, hoistway plumb checking, and precision mechanical commissioning',
      ],
      workflowSteps: [
        { step: '01', title: 'Architectural Shaft Review', desc: 'Verification of hoistway dimensions, pit depth, overhead height, and structural beams.' },
        { step: '02', title: 'Fabrication & Delivery', desc: 'High-grade car frame, guide rail, and drive machine manufacturing.' },
        { step: '03', title: 'Mechanical & Electrical Erection', desc: 'Precision laser alignment of rails, cab assembly, and controller wiring.' },
        { step: '04', title: 'Operational Commissioning & Handover', desc: 'Full-load drop testing, safety mechanism verification, and warranty activation.' },
      ],
      equipmentBrands: ['NSE SMART Systems', 'Schindler', 'KONE', 'OTIS', 'Johnson'],
      faqs: [
        { question: 'How long does a new elevator installation take?', answer: 'A typical 6-to-10 passenger residential elevator installation takes approximately 4 to 6 weeks following hoistway civil handover.' },
      ],
      status: 'published',
    },
  ];

export const FALLBACK_LOCATIONS: any[] = [
    {
      slug: 'elevator-repair-navi-mumbai',
      cityName: 'Navi Mumbai',
      state: 'Maharashtra',
      metaTitle: 'Lift Maintenance & 24/7 Repair in Navi Mumbai | NSE',
      metaDescription: 'Trusted lift AMC maintenance, repairs & modernization in Navi Mumbai. Head office in Airoli, covering Vashi, Belapur & Panvel. Call/WhatsApp +91 90499 94679.',
      slaMinutes: 30,
      branchAddress: 'Airoli, Navi Mumbai, Maharashtra',
      branchPhone: '+91 90499 94679',
      coveredZips: ['400708', '400703', '400705', '400709', '400706', '410206'],
      countiesServed: ['Airoli', 'Vashi', 'Kopar Khairane', 'Ghansoli', 'Mahape MIDC', 'CBD Belapur', 'Panvel'],
      licenseNumbers: ['24/7 Field Rapid Dispatch', 'Rapid Response SLA'],
      regulatoryAuthority: 'Navi Mumbai Regional Operations Hub',
      coordinates: { latitude: 19.1558, longitude: 72.9986 },
      localFaqs: [
        { question: 'What areas in Navi Mumbai does your Airoli headquarters service?', answer: 'Our rapid-response service vans cover Airoli, Vashi, Kopar Khairane, Ghansoli, Mahape, Nerul, Belapur, Kharghar, and Panvel with prompt dispatch.' },
        { question: 'Do you provide lift AMC contracts for high-rise societies in Navi Mumbai?', answer: 'Yes. We manage AMC maintenance contracts for residential cooperative housing societies and commercial complexes throughout Navi Mumbai.' },
      ],
      status: 'published',
    },
    {
      slug: 'elevator-repair-pune',
      cityName: 'Pune',
      state: 'Maharashtra',
      metaTitle: 'Lift Maintenance & 24/7 Repair in Pune | NSE',
      metaDescription: 'Lift AMC maintenance & 24/7 emergency repair in Pune & PCMC. Serving Hinjewadi, Baner, Wakad, Hadapsar, Ravet, Punavale & Chinchwad. Call/WhatsApp +91 90499 94679.',
      slaMinutes: 30,
      branchAddress: 'Pune Regional Operations Depot, Pune, Maharashtra – 411046',
      branchPhone: '+91 90499 94679',
      coveredZips: ['411046', '411043', '411037', '411041', '411038', '411001'],
      countiesServed: [
        'Hinjewadi',
        'Baner',
        'Wakad',
        'Hadapsar',
        'Ravet',
        'Punavale',
        'Tathawade',
        'Chinchwad',
        'Pashan',
        'Mamurdi',
        'Marunji',
        'Nere',
      ],
      licenseNumbers: ['15+ Certified Engineers', '24/7 Motorized Response Units'],
      regulatoryAuthority: 'Pune Regional Operations Hub',
      coordinates: { latitude: 18.5204, longitude: 73.8567 },
      localFaqs: [
        { question: 'How quickly can your Pune service team arrive in Wakad, Baner, or Hinjewadi?', answer: 'Our mobile field engineering units are strategically positioned across Pune and PCMC to reach Hinjewadi, Baner, Wakad, Hadapsar, and PCMC corridors with rapid emergency dispatch.' },
        { question: 'Which areas in Pune and PCMC are covered under your 24/7 lift AMC?', answer: 'We provide comprehensive 24/7 AMC and breakdown response across Pune and PCMC corridors, including Hinjewadi, Baner, Wakad, Hadapsar, Ravet, Punavale, Tathawade, Pashan, Mamurdi, Marunji, Nere, and Chinchwad.' },
      ],
      status: 'published',
    },
  ];

export const FALLBACK_INDUSTRIES: any[] = [
    {
      slug: 'residential-high-rises-condos',
      name: 'Co-operative Housing Societies (CHS) & High-Rises',
      metaTitle: 'Housing Society Lift AMC Maintenance in Mumbai & Pune | NSE',
      metaDescription: 'Reliable 24/7 lift AMC maintenance for Co-operative Housing Societies (CHS) and residential towers. Rapid entrapment rescue, genuine OEM spares.',
      description: 'Residential housing societies depend heavily on lift reliability for families, senior citizens, and children. We provide peace of mind to managing committees and residents with predictable AMC pricing.',
      relatedServices: ['elevator-maintenance', 'elevator-repair', 'elevator-cab-remodeling'],
      criticalChallenges: [
        'Panic and safety risks from passenger entrapment incidents during power cuts',
        'Exorbitant OEM spare parts pricing and slow response times',
        'Managing committee accountability for building safety and transparent maintenance records',
      ],
      vanguardSolutions: [
        'Rapid 24/7 emergency response dispatch across Navi Mumbai and Pune',
        'Genuine OEM spares at ~30% lower cost than typical OEM direct pricing',
        'Comprehensive safety audit readiness and digital maintenance logbooks',
      ],
      faqs: [
        { question: 'Can our housing society switch our AMC to NSE from our OEM?', answer: 'Yes. We facilitate seamless AMC transitions for housing societies with zero downtime, conducting a free 25-point audit before taking over service.' },
      ],
      status: 'published',
    },
    {
      slug: 'commercial-office-buildings',
      name: 'Commercial Towers & IT Business Parks',
      metaTitle: 'Commercial Building Elevator AMC Maintenance | NSE',
      metaDescription: 'High-traffic commercial building and IT park lift maintenance contracts. 99.8% uptime, destination dispatch, and rapid breakdown response.',
      description: 'Commercial buildings and IT parks demand peak lift performance during morning and evening rush hours. Our preventative maintenance schedules eliminate mid-day shutdowns.',
      relatedServices: ['elevator-maintenance', 'elevator-modernization'],
      criticalChallenges: [
        'Heavy employee transit congestion causing floor delays and frustration',
        'Unpredictable OEM repair delays from overseas spare backorders',
        'Complex coordination with building facility managers',
      ],
      vanguardSolutions: [
        'Off-peak preventative maintenance schedules during weekends or night shifts',
        'Dedicated senior field engineer assigned to your commercial facility',
        'Multi-brand expertise across Schindler, KONE, OTIS, and Johnson lifts',
      ],
      faqs: [
        { question: 'Do you conduct servicing outside normal office hours?', answer: 'Yes. We coordinate with facility teams to perform monthly maintenance during weekends or off-peak hours.' },
      ],
      status: 'published',
    },
    {
      slug: 'hospital-healthcare-elevators',
      name: 'Hospitals & Healthcare Stretcher Lifts',
      metaTitle: 'Hospital Stretcher Lift Maintenance & Repair | NSE',
      metaDescription: 'Mission-critical hospital bed lift maintenance, ultra-smooth digital floor leveling, and 24/7 priority emergency response in Mumbai & Pune.',
      description: 'Healthcare facilities require flawless elevator operation for patient stretcher transit, sterile medical equipment, and intensive care access.',
      relatedServices: ['elevator-maintenance', 'hydraulic-traction-conversions'],
      criticalChallenges: [
        'Zero tolerance for stretcher lift downtime during medical emergencies',
        'Jarring floor stops causing discomfort or danger to critical patients',
        'Stringent hygiene and clean machine room requirements',
      ],
      vanguardSolutions: [
        'Highest priority 24/7 emergency dispatch with immediate technician routing',
        'Precision closed-loop leveling accurate within 3mm of landing floor sills',
        'Hygiene-compliant stainless steel cab panel refurbishment',
      ],
      faqs: [
        { question: 'How do you ensure smooth floor leveling for hospital stretchers?', answer: 'We calibrate variable frequency drives and digital floor sensors to guarantee jerk-free stops perfectly level with hospital corridor floors.' },
      ],
      status: 'published',
    },
    {
      slug: 'hotel-hospitality-elevators',
      name: 'Hotels & Luxury Hospitality Properties',
      metaTitle: 'Hotel Elevator Maintenance & Modernization | NSE',
      metaDescription: 'Quiet, premium elevator maintenance for hotels, banquet halls, and luxury hospitality venues across Mumbai and Pune.',
      description: 'In hospitality, a single out-of-order elevator damages guest experience and online review ratings. We ensure silent, smooth, and dependable vertical transit.',
      relatedServices: ['elevator-maintenance', 'elevator-cab-remodeling'],
      criticalChallenges: [
        'Guest complaints and review downgrades from elevator breakdowns',
        'Noise and vibration disturbing hotel rooms near the lift shaft',
        'Heavy luggage cart scuffs damaging car interior panels',
      ],
      vanguardSolutions: [
        'Vibration damping pads and whisper-quiet door operator calibration',
        'Scratch-resistant stainless steel cladding and heavy-duty bumper rails',
        'Flexible servicing mapped strictly around guest checkout hours',
      ],
      faqs: [
        { question: 'Can you eliminate motor vibration that disturbs guest rooms?', answer: 'Yes. We install vibration isolation pads under machine beds and adjust motor drive frequencies to eliminate hum.' },
      ],
      status: 'published',
    },
    {
      slug: 'education-campuses',
      name: 'Universities & Educational Campuses',
      metaTitle: 'Campus Elevator Servicing & Safety Audits | NSE',
      metaDescription: 'Durable elevator maintenance for colleges, school campuses, and university residence halls in Pune and Navi Mumbai.',
      description: 'Educational campuses experience high passenger surges between lectures. We keep campus elevator fleets running safely with robust safety interlocks.',
      relatedServices: ['elevator-maintenance', 'safety-inspections-code-compliance'],
      criticalChallenges: [
        'Surge traffic cycles between class schedules causing door cycling wear',
        'Tampering and rough usage of pushbuttons and door safety edges',
        'Strict safety compliance requirements for student welfare',
      ],
      vanguardSolutions: [
        'Heavy-duty multi-beam infrared door curtain sensors preventing door damage',
        'Vandal-resistant stainless steel buttons and durable fixtures',
        'Comprehensive campus maintenance contracts with single-point dispatch',
      ],
      faqs: [
        { question: 'Can you service multiple elevator units across a large campus?', answer: 'Yes. We manage multi-building educational campus contracts with dedicated technicians assigned to the premises.' },
      ],
      status: 'published',
    },
    {
      slug: 'industrial-freight-elevators',
      name: 'Industrial MIDC Plants & Freight Warehouses',
      metaTitle: 'Industrial Goods Lift & Freight Elevator Maintenance | NSE',
      metaDescription: 'Heavy-duty industrial goods lift maintenance, hydraulic cargo hoist repairs, and safety compliance across MIDC corridors in Maharashtra.',
      description: 'Factories in MIDC corridors rely on heavy goods lifts to transport raw materials and finished inventory. We keep heavy freight moving safely.',
      relatedServices: ['hydraulic-traction-conversions', 'elevator-maintenance'],
      criticalChallenges: [
        'Heavy shock loading from pallet trucks and forklift transit',
        'Industrial dust and moisture contaminating hoistway switches',
        'High motor duty cycles causing thermal overloads',
      ],
      vanguardSolutions: [
        'Reinforced platform sill structures and heavy-duty landing interlocks',
        'Dust-resistant sealed electrical enclosures and ruggedized limit switches',
        'Heavy mechanical gearbox overhauls and calibrated high-tensile wire ropes',
      ],
      faqs: [
        { question: 'Do you repair heavy industrial goods lifts in MIDC industrial zones?', answer: 'Yes. We service goods elevators in Bhosari MIDC, Chakan, Mahape MIDC, and Taloja industrial areas.' },
      ],
      status: 'published',
    },
  ];

export const FALLBACK_CASE_STUDIES: any[] = [
    {
      slug: 'greenfield-heights-amc-takeover',
      buildingName: 'Greenfield Heights CHS',
      city: 'Airoli, Navi Mumbai',
      metaTitle: 'Case Study: Greenfield Heights CHS AMC Takeover | NSE',
      metaDescription: 'How Greenfield Heights CHS reduced breakdowns by 92% and cut elevator maintenance costs by 31% with NSE multi-brand AMC.',
      scope: 'Multi-Brand AMC Takeover, Preventative Overhaul, Genuine Spares Protocol',
      units: '8 High-Rise Passenger Elevators (16 Floors)',
      angleTag: 'Cost Savings',
      problem: 'The 8-wing housing society was paying excessive fees to a legacy OEM contractor who repeatedly delayed critical door drive replacements. This caused frequent shutdowns and heated resident disputes during morning office commute hours.',
      solution: 'NSE assumed comprehensive maintenance across the 8-car fleet, replaced worn landing interlocks with genuine OEM spares, established an on-site emergency spare parts locker, and instituted monthly 25-point preventative servicing.',
      resultsSummary: 'Reduced breakdown frequency from 14 monthly calls to under 1, lowered annual society maintenance expenditure by 31%, and sustained 99.8% verified fleet uptime.',
      results: [
        { label: 'Cost Savings', value: '31% vs OEM' },
        { label: 'Breakdown Reduction', value: '92%' },
        { label: 'Fleet Uptime', value: '99.8%' },
      ],
      pullQuote: {
        quote: 'Switching to NSE cut our society elevator expenditure by nearly a third while our lifts finally run without daily morning breakdowns.',
        author: 'Ramesh Thorat',
        role: 'Chairman, Greenfield Heights CHS',
      },
      servicesPerformed: ['elevator-maintenance', 'non-proprietary-elevator-service'],
      images: ['/images/case-studies/greenfield-towers.jpg'],
      isPlaceholder: true,
      status: 'published',
    },
    {
      slug: 'mayflower-residency-safety-audit',
      buildingName: 'Mayflower Residency CHS',
      city: 'Pune, Maharashtra',
      metaTitle: 'Case Study: Mayflower Residency Safety Audit & ARD Modernization | NSE',
      metaDescription: 'How NSE resolved critical ARD failures and eliminated elevator breakdown notices for Mayflower Residency CHS in Pune within 14 days.',
      scope: 'Free 25-Point Safety Audit, ARD Rectification, Brake Relining & Balancing',
      units: '6 Passenger Elevators (12 Floors)',
      angleTag: 'Safety & Compliance',
      problem: 'Following an unannounced state lift inspection, the society received an official compliance notice citing defective Automatic Rescue Devices (ARD) and unverified governor rope tensioning, facing imminent suspension of elevator power.',
      solution: 'NSE conducted a comprehensive 25-point safety audit within 24 hours, replaced exhausted battery banks with high-capacity dry cell ARD packs, recalibrated overspeed governor safety gears, and executed precision full-load drop tests.',
      resultsSummary: 'Resolved all safety and mechanical defects within 14 days, achieved 100% successful emergency battery landings during power cut simulations, and secured reliable daily operation.',
      results: [
        { label: 'Notice Clearance', value: '14 Days' },
        { label: 'ARD Success Rate', value: '100% Tested' },
        { label: 'ARD Reliability', value: '100% Pass Rate' },
      ],
      pullQuote: {
        quote: 'NSE saved our committee from repeated lift shutdowns by rectifying our ARD systems and restoring complete reliability in just two weeks.',
        author: 'Deepak Shirodkar',
        role: 'Hon. Secretary, Mayflower Residency CHS',
      },
      servicesPerformed: ['safety-inspections-code-compliance', 'elevator-repair'],
      images: ['/images/case-studies/mayflower-residency.jpg'],
      isPlaceholder: true,
      status: 'published',
    },
    {
      slug: 'shree-samarth-emergency-rescue',
      buildingName: 'Shree Samarth Horizon CHS',
      city: 'Airoli, Navi Mumbai',
      metaTitle: 'Case Study: Sunday Emergency Entrapment Rescue | NSE',
      metaDescription: 'How NSE 24/7 mobile dispatch responded in 19 minutes on a Sunday evening to safely rescue trapped passengers and restore traction lift operation at Shree Samarth Horizon CHS.',
      scope: '24/7 Rapid Emergency Dispatch, Brake Coil Rewind, Sunday Entrapment Remediation',
      units: '4 High-Rise Traction Elevators (18 Floors)',
      angleTag: 'Emergency Response',
      problem: 'On a stormy Sunday evening, a sudden electrical power surge tripped the main traction brake coil of Tower B primary elevator, leaving four residents trapped between the 9th and 10th floors.',
      solution: 'NSE Navi Mumbai mobile emergency response crew was dispatched immediately, arriving on-site in 19 minutes. Engineers executed manual brake release leveling to evacuate all passengers safely, then installed a replacement coil from mobile van inventory to restore full operation that night.',
      resultsSummary: 'Reached site in 19 minutes, safely evacuated all passengers within 8 minutes of arrival with zero injuries, and restored normal elevator operation in under 2 hours.',
      results: [
        { label: 'Emergency Arrival', value: '19 Mins' },
        { label: 'Passenger Rescue', value: 'Zero Injury' },
        { label: 'Service Restored', value: '< 2 Hours' },
      ],
      pullQuote: {
        quote: 'Their technician was on-site in 19 minutes on a Sunday evening. The calm, professional way they rescued our residents was commendable.',
        author: 'Sanjay More',
        role: 'Managing Committee Member, Shree Samarth Horizon CHS',
      },
      servicesPerformed: ['elevator-repair', 'elevator-maintenance'],
      images: ['/images/case-studies/shree-samarth.jpg'],
      isPlaceholder: true,
      status: 'published',
    },
    {
      slug: 'panchsheel-business-square-modernization',
      buildingName: 'Panchsheel Business Square',
      city: 'Pune, Maharashtra',
      metaTitle: 'Case Study: Turnkey Commercial Elevator Modernization | NSE',
      metaDescription: 'How NSE modernized 4 legacy commercial elevators at Panchsheel Business Square in Pune with VVVF microprocessor drives, cutting energy consumption by 38%.',
      scope: 'Turnkey Microprocessor Upgrade, VVVF Regenerative Drives, Luxury Cab Refurbishment',
      units: '4 Commercial Passenger Lifts (10 Floors)',
      angleTag: 'Modernization',
      problem: 'The commercial tower 20-year-old relay-based elevators suffered from jerky acceleration, ±25mm landing step hazards, loud brake chatter, and high electricity bills, triggering persistent corporate tenant complaints.',
      solution: 'NSE executed a phased turnkey modernization without disrupting business hours. Upgraded obsolete relay panels to digital VVVF microprocessor controllers, installed high-efficiency permanent magnet gearless drives, fitted SS 304 hairline cabs with LED fixtures, and calibrated digital floor sensors.',
      resultsSummary: 'Reduced elevator electricity consumption by 38%, achieved precision floor leveling within ±2mm, and eliminated 75% of cabin ride vibration.',
      results: [
        { label: 'Energy Reduction', value: '38% Lower' },
        { label: 'Leveling Precision', value: '±2 mm' },
        { label: 'Ride Vibration', value: '-75% Reduced' },
      ],
      pullQuote: {
        quote: 'Tenants thought we had installed brand new elevator shafts. The ride is whisper quiet, and our building power bills dropped immediately.',
        author: 'Kishore Bandopadhyaya',
        role: 'Commercial Estate Manager, Panchsheel Business Square',
      },
      servicesPerformed: ['elevator-modernization', 'elevator-cab-remodeling'],
      images: ['/images/case-studies/panchsheel-commercial.jpg'],
      isPlaceholder: true,
      status: 'published',
    },
  ];

export const FALLBACK_BLOG_POSTS: any[] = [
    {
      slug: 'why-proprietary-elevator-software-costs-thousands',
      title: 'Genuine OEM Spares vs. Counterfeit Local Parts: Why Quality Matters for High-Rise Lifts',
      author: 'Sachin Patil',
      authorTitle: 'Chief Technical Officer',
      category: 'Safety & Spares',
      readingTime: '6 min read',
      metaTitle: 'Genuine OEM Elevator Spares Explained | NSE',
      metaDescription: 'Learn why using genuine OEM spare parts for Schindler, KONE, OTIS, and Johnson lifts prevents catastrophic failures and protects housing society budgets.',
      content: 'Using spurious or unverified replacement components in elevator door interlocks, brake solenoids, and traction sheaves poses grave safety hazards for passengers. This guide explains why New Sahyadri Elevator insists on 100% genuine OEM spare parts, preserving safety integrity while saving societies approximately 30% through transparent local engineering.',
      status: 'published',
      publishedAt: new Date('2026-06-15'),
    },
    {
      slug: 'asme-a17-category-1-vs-category-5-testing-explained',
      title: 'Housing Society Elevator Safety & Maintenance: A Managing Committee Guide',
      author: 'Dinesh Shinde',
      authorTitle: 'Compliance & Safety Director',
      category: 'Safety & Maintenance',
      readingTime: '7 min read',
      metaTitle: 'Housing Society Elevator Safety & Maintenance Guide | NSE',
      metaDescription: 'Everything housing society chairmen and secretaries need to know about elevator safety audits, ARD testing, and preventative maintenance schedules.',
      content: 'Housing societies are responsible for maintaining elevator passenger safety and ensuring equipment reliability for all residents. Learn the essential 25-point safety checklist, ARD emergency battery testing protocols, and how to avoid costly emergency breakdowns.',
      status: 'published',
      publishedAt: new Date('2026-07-20'),
    },
    {
      slug: 'warning-signs-hydraulic-elevator-cylinder-failure',
      title: '5 Warning Signs Your Society Elevator Needs Immediate Brake or Wire Rope Service',
      author: 'Pravin Jadhav',
      authorTitle: 'Senior Field Engineer',
      category: 'Preventative Maintenance',
      readingTime: '5 min read',
      metaTitle: 'Elevator Brake and Wire Rope Warning Signs | NSE',
      metaDescription: 'Detect elevator mechanical issues early. Learn the 5 warning signs of brake wear, rope slipping, and jerky leveling before an emergency entrapment occurs.',
      content: 'Early detection of elevator mechanical fatigue prevents passenger entrapments and expensive motor replacements. Watch for unlevel stopping at floor landings, scraping sounds in the hoistway, burning electrical odors, slow door opening cycles, and jerky deceleration.',
      status: 'published',
      publishedAt: new Date('2026-08-01'),
    },
  ];

export const FALLBACK_CAREERS: any[] = [
    {
      slug: 'senior-elevator-service-mechanic',
      title: 'Senior Lift Maintenance Engineer',
      city: 'Pune',
      state: 'Maharashtra',
      location: 'Pune (PCMC & Western Corridors)',
      department: 'Field Operations',
      salaryRange: {
        min: 360000,
        max: 540000,
        display: '₹3,60,000 - ₹5,40,000 / Year + Emergency Allowance',
      },
      description: 'We are seeking an experienced Lift Maintenance Engineer to manage residential society and commercial service routes across South Pune. Attractive compensation, company motorcycle allowance, and safety equipment provided.',
      responsibilities: [
        'Perform monthly preventive AMC servicing on traction and hydraulic lifts',
        'Troubleshoot electrical control panels and door operator mechanisms',
        'Participate in rotating 24/7 on-call breakdown response team',
      ],
      qualifications: [
        'ITI / Diploma in Electrical or Mechanical Engineering',
        'Minimum 4 years of field elevator maintenance experience',
        'Familiarity with Schindler, KONE, OTIS, and Johnson lift systems',
      ],
      employmentType: 'FULL_TIME',
      status: 'published',
      datePosted: new Date('2026-08-01'),
    },
    {
      slug: 'elevator-modernization-lead-technician',
      title: 'Elevator Modernization Lead Technician',
      city: 'Navi Mumbai',
      state: 'Maharashtra',
      location: 'Airoli & Navi Mumbai Corridor',
      department: 'Modernization Engineering',
      salaryRange: {
        min: 420000,
        max: 600000,
        display: '₹4,20,000 - ₹6,00,000 / Year + Performance Bonus',
      },
      description: 'Lead turnkey modernization projects across residential high-rises and commercial complexes in Navi Mumbai. Supervise controller retrofits, VVVF drive upgrades, and safety gear installations.',
      responsibilities: [
        'Lead 2-technician teams executing controller and motor modernization',
        'Wire multi-brand microprocessor control systems and ARD units',
        'Conduct static safety brake testing and electromechanical diagnostic evaluations',
      ],
      qualifications: [
        'Diploma in Electrical Engineering with 5+ years in lift modernization',
        'Deep mastery of lift electrical wiring diagrams and drive parameters',
      ],
      employmentType: 'FULL_TIME',
      status: 'published',
      datePosted: new Date('2026-08-05'),
    },
    {
      slug: 'elevator-safety-audit-engineer',
      title: 'Lift Safety Auditor & Diagnostic Specialist',
      city: 'Pune',
      state: 'Maharashtra',
      location: 'Pune Regional Hub',
      department: 'Safety & Quality Assurance',
      salaryRange: {
        min: 400000,
        max: 580000,
        display: '₹4,00,000 - ₹5,80,000 / Year + Travel Allowance',
      },
      description: 'Conduct 25-point comprehensive health audits, prepare technical diagnostic reports, and support client societies with preventative maintenance roadmaps.',
      responsibilities: [
        'Perform rigorous safety audits across high-rise residential and hospital elevators',
        'Inspect hoisting wire ropes, governor mechanisms, and ARD functionality',
        'Draft technical audit reports with clear photographic recommendations',
      ],
      qualifications: [
        'Extensive knowledge of elevator electromechanical systems and safety standards',
        'Minimum 6 years of technical elevator maintenance or inspection experience',
      ],
      employmentType: 'FULL_TIME',
      status: 'published',
      datePosted: new Date('2026-08-10'),
    },
  ];

export const FALLBACK_TESTIMONIALS: any[] = [
    {
      quote: 'Switching our 4 wings in Airoli to New Sahyadri Elevator has been the best committee decision this year. On a recent Sunday evening when an entrapment occurred, their mobile engineer arrived in exactly 22 minutes, leveled the cab safely, and restored service without fuss. Outstanding reliability.',
      authorName: 'Rajesh Patil',
      jobTitle: 'Chairman, Managing Committee',
      company: 'Sai Saburi Co-operative Housing Society',
      location: 'Airoli, Navi Mumbai',
      buildingPortfolioSize: '4 Wings, 8 Traction Lifts',
      rating: 5,
      isPlaceholder: true,
      status: 'published',
    },
    {
      quote: 'Our previous OEM renewal quote was bleeding our society maintenance funds. NSE stepped in with genuine multi-brand OEM spare parts, transparent quarterly service logs, and saved our society over 31% annually. The lifts run quieter than they have in years.',
      authorName: 'Anand Kulkarni',
      jobTitle: 'Hon. Secretary',
      company: 'Greenfield Heights CHS',
      location: 'Pune, Maharashtra',
      buildingPortfolioSize: '14-Story Tower, 3 Passenger Lifts',
      rating: 5,
      isPlaceholder: true,
      status: 'published',
    },
    {
      quote: 'In a surgical hospital, jerky stops and unlevel car landings are unacceptable when transporting post-op stretchers. NSE recalibrated our hydraulic valve blocks and VVVF drives, achieving precision floor leveling within ±2mm. Their scheduled 2 AM servicing avoids patient transit hours.',
      authorName: 'Dr. Meena Iyer',
      jobTitle: 'Medical Director & Facilities Head',
      company: 'Apex Healthcare Center',
      location: 'Vashi, Navi Mumbai',
      buildingPortfolioSize: 'Hospital Facility, 4 Bed Lifts',
      rating: 5,
      isPlaceholder: true,
      status: 'published',
    },
    {
      quote: 'Managing 12 passenger elevators across two major OEM makes was a logistical nightmare with separate contractors. NSE unified our entire fleet under one comprehensive AMC. Their technicians carry genuine spare boards and relays in their service van, cutting our MTTR by 60%.',
      authorName: 'Vikram Malhotra',
      jobTitle: 'Facility Operations Lead',
      company: 'Millennium IT Park',
      location: 'Mahape, Navi Mumbai',
      buildingPortfolioSize: 'Commercial IT Park, 12 High-Speed Lifts',
      rating: 5,
      isPlaceholder: true,
      status: 'published',
    },
    {
      quote: 'Very professional technical crew. They conducted a free 25-point audit that caught a worn governor cable our former contractor ignored. Resolving an initial invoice clarification took a couple of extra days, but their management handled it transparently. Highly trustworthy team.',
      authorName: 'Suresh Deshpande',
      jobTitle: 'Treasurer',
      company: 'Mayflower Park CHS',
      location: 'Pune, Maharashtra',
      buildingPortfolioSize: '7-Story Complex, 4 Lifts',
      rating: 4,
      isPlaceholder: true,
      status: 'published',
    },
    {
      quote: 'Our 18-year-old lifts were shaking and alarming our senior citizen residents. NSE executed a modern VVVF microprocessor upgrade and cab refurbishment in under 5 days per shaft. The ride is now whisper-quiet and silky smooth, with integrated ARD battery backup.',
      authorName: 'Sunita Jadhav',
      jobTitle: 'Secretary',
      company: 'Greenfield Co-operative Housing Society',
      location: 'Baner, Pune',
      buildingPortfolioSize: 'Residential CHS, 2 Traction Lifts',
      rating: 5,
      isPlaceholder: true,
      status: 'published',
    },
    {
      quote: 'When a 3-ton freight lift breaks down mid-shift, dispatch stops. NSE answered our emergency callback on a Saturday morning, replaced a sheared landing interlock switch within 35 minutes, and kept our shipping docks on schedule. Genuine industrial expertise.',
      authorName: 'Manoj Narvekar',
      jobTitle: 'Logistics & Plant Operations Manager',
      company: 'Swastik Industrial Logistics',
      location: 'Taloja MIDC, Navi Mumbai',
      buildingPortfolioSize: 'Industrial Warehouse, 2 Heavy Freight Hoists',
      rating: 4,
      isPlaceholder: true,
      status: 'published',
    },
    {
      quote: 'We faced persistent emergency power issues due to an uncalibrated ARD unit under our previous vendor. NSE diagnosed the battery pack issue immediately, performed complete load drop tests, and achieved 100% emergency rescue reliability in record time.',
      authorName: 'Prashant Shinde',
      jobTitle: 'Managing Committee Member',
      company: 'Sunrise Heights CHS',
      location: 'Pimpri-Chinchwad, Pune',
      buildingPortfolioSize: '10-Story Society, 4 Passenger Lifts',
      rating: 5,
      isPlaceholder: true,
      status: 'published',
    },
  ];
